on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: rector

jobs:
  rector:
    uses: reagordi/actions/.github/workflows/rector.yml@master
    secrets:
      token: ${{ secrets.REAGORDI_GITHUB_TOKEN }}
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.3']
